# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
	config.ssh.insert_key = false
	
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end
	
	config.vm.define "AWSLightGrid" do |server|
		#server.vm.network "forwarded_port", guest: 5252, host: 5252
		#server.vm.network "forwarded_port", guest: 80, host: 8080
		#server.vm.network "forwarded_port", host_ip: "127.0.0.1", host: 4141, guest_ip: "127.0.0.1", guest: 4040
		server.vm.network "private_network", ip:"192.168.10.95"

    server.vm.synced_folder "./filestocopy", "/vagrant_filestocopy"
		server.vm.synced_folder "../src/web_app", "/vagrant_web_app"
    server.vm.synced_folder "../src/socket_server", "/vagrant_socket_server"

		server.vm.provision "file",
			source: "../network/ngrok.yml",
			destination: "~/ngrok/ngrok.yml"

    server.vm.provision "file",
			source: "./filestocopy/ngrok/ngrok",
			destination: "~/ngrok/ngrok"

		server.vm.provision "shell" do |s|
			s.inline = "rm -rf /ngrok; mv /home/vagrant/ngrok /ngrok;chown -R vagrant:vagrant /ngrok;chmod 755 /ngrok/ngrok"
			s.privileged = true
		end

		server.vm.provision "chef_solo" do |chef|
			chef.add_recipe "hosts"
			chef.add_recipe "aptupdate"
			chef.add_recipe "vim"
			chef.add_recipe "apache"
			chef.add_recipe "python"
			chef.add_recipe "pip"
			chef.add_recipe "nodejs"
      chef.add_recipe "ngrok"
      chef.add_recipe "paho-mqtt"
      chef.add_recipe "mosquitto"

		end

		
	end
end