# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.ssh.insert_key = false
	
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end
	
	config.vm.define "cfn-sns-endpoint" do |cfn_sns|
		cfn_sns.vm.network "forwarded_port", guest: 80, host:9000
		cfn_sns.vm.synced_folder "./apache-configs", "/vagrant_apache_configs"
		cfn_sns.vm.synced_folder "./src", "/vagrant_source"
		cfn_sns.vm.provision "chef_solo" do |chef|
			chef.add_recipe "hosts"
			chef.add_recipe "firewall"
			chef.add_recipe "aptupdate"
			chef.add_recipe "vim"
			chef.add_recipe "apache"
			chef.add_recipe "mod_wsgi"
			chef.add_recipe "python"
			chef.add_recipe "pip"
			chef.add_recipe "flask"
			chef.add_recipe "uuid"
			chef.add_recipe "requests"
			chef.add_recipe "M2Crypto"
		end
	end
end
